heroku buildpack meteor

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,54 +1,84 @@
 #!/bin/sh
 
-BUILD_DIR=$1
-CACHE_DIR=$2
-METEOR_HOME=$BUILD_DIR/.meteor/local
-PATH=$METEOR_HOME/usr/bin:$METEOR_HOME/usr/lib/meteor/bin:$PATH
+# Meteor Heroku buildpack for Meteor 0.9.3+.
 
-# Unfortunately heroku buildpacks don't let you pass parameters
-# to this script, so if you want to change the version of meteor,
-# you'll have to fork and hard-code this.
-METEOR_VERSION=0.9.4
+# fail fast.
+set -e
+# debug verbosely.
+#set -x
 
-fetch_meteor() {
-#  if [ -f "$METEOR_HOME/usr/bin/meteor" ] ; then
-    # Skip if meteor is already fetched
-#    return
-#  fi
+# Get the path to dir one above this file.
+BUILDPACK_DIR=$(cd -P -- "$(dirname -- "$0")" && cd .. && pwd -P)
+# Get the directory our app is checked out in (the "BUILD_DIR"), passed by Heroku
+APP_CHECKOUT_DIR=$1
+# Where we will install meteor. Has to be outside the APP_CHECKOUT_DIR.
+METEOR_DIR=`mktemp -d "$BUILDPACK_DIR"/meteor-XXXX`
+# Where we'll put things we compile.
+COMPILE_DIR_SUFFIX=".meteor/heroku_build"
+COMPILE_DIR="$APP_CHECKOUT_DIR"/"$COMPILE_DIR_SUFFIX"
 
+# Create directories as needed.
+mkdir -p "$APP_CHECKOUT_DIR" "$METEOR_DIR" "$COMPILE_DIR"
 
-#  PACKAGE=meteor_${METEOR_VERSION}-1_amd64.deb
+# Update the path so we get npm, etc.
+PATH="$COMPILE_DIR/bin:$PATH"
 
-  echo "Fetching meteor deb package"
-#  curl -o "$CACHE_DIR/$PACKAGE" "http://d3sqy0vbqsdhku.cloudfront.net/${PACKAGE}"
-  
-  curl https://install.meteor.com/ | sh
+#
+# Install node
+#
+echo "-----> Installing node"
+NODE_VERSION=`curl -sS --get https://semver.io/node/resolve`
+NODE_URL="http://s3pository.heroku.com/node/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz"
+curl -sS $NODE_URL -o - | tar -zxf - -C $COMPILE_DIR --strip 1
+# Export some environment variables for npm to use when compiling stuff.
+export npm_config_prefix="$COMPILE_DIR"
+export CPATH="$COMPILE_DIR"/include
+export CPPPATH="$CPATH"
 
-#  echo "Unpacking meteor"
-#  [ ! -d "$METEOR_HOME" ] && mkdir -p "$METEOR_HOME"
-#  ar p "$CACHE_DIR/$PACKAGE" data.tar.gz | tar -C "$METEOR_HOME" -zxf -
-}
+#
+# Install meteor
+#
+echo "-----> Installing meteor"
+curl -sS https://install.meteor.com | HOME="$METEOR_DIR" /bin/sh
+METEOR="$METEOR_DIR/.meteor/meteor" # The meteor binary.
 
-build() {
-  ( 
-    cd $BUILD_DIR
-    echo "Building meteor bundle"
-    meteor bundle $CACHE_DIR/bundle.tar.gz 
-    mkdir -p $BUILD_DIR/.meteor/local/build
-    tar -zxf $CACHE_DIR/bundle.tar.gz --strip-components 1 -C $BUILD_DIR/.meteor/local/build
-    rm $CACHE_DIR/bundle.tar.gz
-  )
-}
+#
+# Build the meteor app!
+#
+echo "-----> Bundling bundle"
+cd $APP_CHECKOUT_DIR
 
-[ ! -d $BUILD_DIR ] && mkdir $BUILD_DIR
-[ ! -d $CACHE_DIR ] && mkdir $CACHE_DIR
+# Now on to bundling. Don't put the bundle in $APP_CHECKOUT_DIR, or it will
+# recurse, trying to bundle up its own bundling.
+BUNDLE_DEST=`mktemp -d "$BUILDPACK_DIR/build-XXXX"`
+HOME=$METEOR_DIR $METEOR build --directory $BUNDLE_DEST
+mv $BUNDLE_DEST/bundle "$COMPILE_DIR/app"
+rmdir $BUNDLE_DEST
 
-fetch_meteor
-build
-
-echo "Checking for post_compile script"
-if [ -f $BUILD_DIR/bin/post_compile ] ; then
-    echo "-----> Running post_compile hook"
-    chmod +x $BUILD_DIR/bin/post_compile
-    $BUILD_DIR/bin/post_compile
+# If we use npm, run npm install.
+if [ -e "$COMPILE_DIR"/app/programs/server/package.json ]; then
+  cd "$COMPILE_DIR"/app/programs/server && npm install
 fi
+
+#
+# Environment
+#
+# Add an export of PATH which includes our compile dir.
+echo "-----> Adding PATH environment"
+mkdir -p "$APP_CHECKOUT_DIR"/.profile.d
+cat > "$APP_CHECKOUT_DIR"/.profile.d/path.sh <<EOF
+  #!/bin/sh
+  export PATH=\$HOME/$COMPILE_DIR_SUFFIX/bin:\$PATH
+  export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:\$HOME/$COMPILE_DIR_SUFFIX/lib
+EOF
+
+#
+# Extras
+#
+
+# source scripts in 'extra' dir, if any.  Create them for custom stuff like
+# binary dependencies, phantomjs for spiderable, etc.
+echo "-----> Running extras"
+for file in `ls "$BUILDPACK_DIR"/extra | sort`; do
+    . "$BUILDPACK_DIR"/extra/$file 
+done
