with meteorite

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,85 +1,165 @@
-#!/bin/sh
+#!/usr/bin/env bash
+# bin/compile <build-dir> <cache-dir>
 
-# Meteor Heroku buildpack for Meteor 0.9.3+.
-
-# fail fast.
+# fail fast
 set -e
-# debug verbosely.
-#set -x
 
-# Get the path to dir one above this file.
-BUILDPACK_DIR=$(cd -P -- "$(dirname -- "$0")" && cd .. && pwd -P)
-# Get the directory our app is checked out in (the "BUILD_DIR"), passed by Heroku
-APP_CHECKOUT_DIR=$1
-# Where we will install meteor. Has to be outside the APP_CHECKOUT_DIR.
-# METEOR_DIR=`mktemp -d "$BUILDPACK_DIR"/meteor-0.9.4`
-METEOR_DIR="$BUILDPACK_DIR/meteor-0.9.4"
-# Where we'll put things we compile.
-COMPILE_DIR_SUFFIX=".meteor/heroku_build"
-COMPILE_DIR="$APP_CHECKOUT_DIR"/"$COMPILE_DIR_SUFFIX"
+# debug
+# set -x
 
-# Create directories as needed.
-mkdir -p "$APP_CHECKOUT_DIR" "$METEOR_DIR" "$COMPILE_DIR"
+# clean up leaking environment
+unset GIT_DIR
 
-# Update the path so we get npm, etc.
-PATH="$COMPILE_DIR/bin:$PATH"
+# parse and derive params
+BUILD_DIR=$1
+CACHE_DIR=$2
+LP_DIR=`cd $(dirname $0); cd ..; pwd`
 
-#
-# Install node
-#
-echo "-----> Installing node"
-NODE_VERSION=`curl -sS --get https://semver.io/node/resolve`
-NODE_URL="http://s3pository.heroku.com/node/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz"
-curl -sS $NODE_URL -o - | tar -zxf - -C $COMPILE_DIR --strip 1
-# Export some environment variables for npm to use when compiling stuff.
-export npm_config_prefix="$COMPILE_DIR"
-export CPATH="$COMPILE_DIR"/include
-export CPPPATH="$CPATH"
+[ ! -d $BUILD_DIR ] && mkdir $BUILD_DIR
+[ ! -d $CACHE_DIR ] && mkdir $CACHE_DIR
 
-#
-# Install meteor
-#
-echo "-----> Installing meteor"
-curl -sS https://install.meteor.com | HOME="$METEOR_DIR" /bin/sh
-METEOR="$METEOR_DIR/.meteor/meteor" # The meteor binary.
+function error() {
+  echo " !     $*"
+  exit 1
+}
 
-#
-# Build the meteor app!
-#
-echo "-----> Bundling bundle"
-cd $APP_CHECKOUT_DIR
+function mktmpdir() {
+  dir=$(mktemp -t node-$1-XXXX)
+  rm -rf $dir
+  mkdir -p $dir
+  echo $dir
+}
 
-# Now on to bundling. Don't put the bundle in $APP_CHECKOUT_DIR, or it will
-# recurse, trying to bundle up its own bundling.
-BUNDLE_DEST=`mktemp -d "$BUILDPACK_DIR/build-XXXX"`
-HOME=$METEOR_DIR $METEOR build --directory $BUNDLE_DEST
-mv $BUNDLE_DEST/bundle "$COMPILE_DIR/app"
-rmdir $BUNDLE_DEST
+function indent() {
+  c='s/^/       /'
+  case $(uname) in
+    Darwin) sed -l "$c";;
+    *)      sed -u "$c";;
+  esac
+}
 
-# If we use npm, run npm install.
-if [ -e "$COMPILE_DIR"/app/programs/server/package.json ]; then
-  cd "$COMPILE_DIR"/app/programs/server && npm install
+function run_npm() {
+  command="$1"
+
+  cd "$BUILD_DIR"
+  HOME="$BUILD_DIR" $VENDORED_NODE/bin/node $VENDORED_NODE/bin/npm $command 2>&1 | indent
+
+  if [ "${PIPESTATUS[*]}" != "0 0" ]; then
+    echo " !     Failed to $command dependencies with npm"
+    exit 1
+  fi
+}
+
+function run_npm2() {
+  command="$1"
+
+  cd "$BUILD_DIR2"
+  HOME="$BUILD_DIR2" $VENDORED_NODE/bin/node $VENDORED_NODE/bin/npm $command 2>&1 | indent
+
+  if [ "${PIPESTATUS[*]}" != "0 0" ]; then
+    echo " !     Failed to $command dependencies with npm"
+    exit 1
+  fi
+}
+
+function package_download() {
+  engine="$1"
+  version="$2"
+  location="$3"
+
+  mkdir -p $location
+  package="http://s3pository.heroku.com/$engine/v$version/$engine-v$version-linux-x64.tar.gz"
+  echo " - downloading and extracting $engine from $package" | indent
+  curl $package -s -o - | tar -zxf  - -C $location --strip 1
+}
+
+echo "-----> Resolving engine versions"
+
+#TODO: Fix package.json loading
+#if [ -f "${BUILD_DIR}/package.json" ]; then
+#  requested_node_ver=$(cat $BUILD_DIR/package.json | $LP_DIR/vendor/jq -r .engines.node)
+#fi
+#temporary - load from nodeversion
+requested_node_ver=""
+if [ -f "${BUILD_DIR}/nodeversion" ]; then
+  echo " - nodeversion file detected, using for semvar" | indent
+  requested_node_ver=$(cat $BUILD_DIR/nodeversion)
+  echo " - requested version: $requested_node_ver" | indent
+fi
+# add a warning if no version of node specified
+if [ "$requested_node_ver" == "" ]; then
+  requested_node_ver="0.10.29"
+  echo
+  echo "No version of Node.js specified in nodeversion, using '${requested_node_ver}'" | indent
+  echo
 fi
 
-#
-# Environment
-#
-# Add an export of PATH which includes our compile dir.
-echo "-----> Adding PATH environment"
-mkdir -p "$APP_CHECKOUT_DIR"/.profile.d
-cat > "$APP_CHECKOUT_DIR"/.profile.d/path.sh <<EOF
+NODE_VERSION=$(curl --silent --get --data-urlencode "range=${requested_node_ver}" https://semver.io/node/resolve)
+echo "Using Node.js version: ${NODE_VERSION}" | indent
+
+# vendor directories
+VENDORED_NODE="$(mktmpdir node)"
+VENDORED_MODULES="$(mktmpdir modules)"
+
+# download and unpack packages
+echo "-----> Fetching Node.js binaries"
+package_download "node" "${NODE_VERSION}" "${VENDORED_NODE}"
+
+# setting up paths for building
+PATH="$VENDORED_NODE/bin:$VENDORED_MODULES/bin:$PATH"
+INCLUDE_PATH="$VENDORED_NODE/include"
+export npm_config_prefix="$VENDORED_MODULES"
+export CPATH="$INCLUDE_PATH"
+export CPPPATH="$INCLUDE_PATH"
+
+
+############################################
+# install meteorite
+############################################
+echo "-----> Installing meteorite with npm"
+
+run_npm "install meteorite -g"
+echo "Meteorite installed" | indent
+
+METEOR_BUILD_DIR="$BUILD_DIR/.meteor/heroku_build"
+mkdir -p "$HOME"
+############################################
+# install meteor + packages through mrt
+# bundle, and install into app/
+############################################
+cd $BUILD_DIR
+echo "Installing meteor" | indent
+
+# Using different folder to prevent install script form deleting packages file
+VENDORED_METEOR="$(mktmpdir meteor)"
+curl https://install.meteor.com | HOME="$VENDORED_METEOR" /bin/sh | indent
+echo "Meteor installed" | indent
+
+echo "Installing packages" | indent
+HOME="$BUILD_DIR" mrt install --force | indent
+echo "Building meteor bundle" | indent
+HOME="$VENDORED_METEOR" "$VENDORED_METEOR"/.meteor/meteor build "$CACHE_DIR"/bundle.tar.gz 2>&1 | indent
+
+mkdir -p "$METEOR_BUILD_DIR"/app
+tar -zxf "$CACHE_DIR"/bundle.tar.gz --strip-components 1 -C "$METEOR_BUILD_DIR"/app
+rm "$CACHE_DIR"/bundle.tar.gz
+BUILD_DIR2="$METEOR_BUILD_DIR"/app/bundle/programs/server
+run_npm2 "install"
+############################################
+
+############################################
+# Prepare ENV vars
+############################################
+echo "Setting up MONGO_URL in .profile.d"
+mkdir -p "$BUILD_DIR"/.profile.d
+cat > "$BUILD_DIR"/.profile.d/mongo.sh <<EOF
   #!/bin/sh
-  export PATH=\$HOME/$COMPILE_DIR_SUFFIX/bin:\$PATH
-  export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:\$HOME/$COMPILE_DIR_SUFFIX/lib
+
+  export MONGO_URL=\${MONGO_URL:-\$MONGOHQ_URL};
 EOF
 
-#
-# Extras
-#
-
-# source scripts in 'extra' dir, if any.  Create them for custom stuff like
-# binary dependencies, phantomjs for spiderable, etc.
-echo "-----> Running extras"
-for file in `ls "$BUILDPACK_DIR"/extra | sort`; do
-    . "$BUILDPACK_DIR"/extra/$file 
-done
+# vendor node into the slug
+PATH="$METEOR_BUILD_DIR/bin:$PATH"
+echo "-----> Vendoring node into slug"
+mkdir -p "$METEOR_BUILD_DIR/bin"
+cp "$VENDORED_NODE/bin/node" "$METEOR_BUILD_DIR/bin/node"
